application: browserstatsall
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static/

- url: /serviceworker.js
  static_dir: ../

libraries:
- name: webapp2
  version: "2.5.1"
